# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 19:06
from __future__ import unicode_literals

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0008_auto_20160224_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_updating_progress',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='progress_data',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('INPROGRESS', 'In Progress'), ('FAILED', 'Failed'), ('SUCCESS', 'Succeeded')], default='PENDING', max_length=15),
        ),
    ]
