# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_q', '0009_auto_20160811_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress_fraction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
